on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy presentation
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set-up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build diagrams
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: ./src/diagrams/*.puml
          message: "Render PlantUML diagrams"
      - name: Build slide show
        run: npm run build:slideshow
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
